<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Content for a request is either generated by the AI Content Generator or
 * written by the brand team and handed over as a sheet. The request has to say
 * which, otherwise the content team has no idea whether to wait for a file.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('product_requests', function (Blueprint $table) {
            $table->boolean('use_ai_content')->default(true)->after('photoshoot_scheduled_at');
        });

        Schema::table('product_request_attachments', function (Blueprint $table) {
            // 'reference' = mood/reference images, 'content' = the brand team's
            // content sheet. Kept on one table so the audit trail stays in one place.
            $table->string('kind', 20)->default('reference')->after('user_id')->index();
        });
    }

    public function down(): void
    {
        Schema::table('product_requests', function (Blueprint $table) {
            $table->dropColumn('use_ai_content');
        });

        Schema::table('product_request_attachments', function (Blueprint $table) {
            $table->dropColumn('kind');
        });
    }
};
