<?php

/*
|--------------------------------------------------------------------------
| Product tag taxonomy, per store
|--------------------------------------------------------------------------
|
| The fixed tag sets the AI Content review screen offers, keyed first by the
| store's shopify_domain (the same key config/product_request_sync.php uses),
| then by category, then by product type. These replace the free-form tags
| Gemini used to invent: a store's tag vocabulary is a merchandising
| decision, not something a model should guess at.
|
| Every store runs its own vocabulary — Bluesalon's categories and tags mean
| nothing on Paris Gallery — so a store absent from this file simply gets no
| tag picker, and the review screen says so rather than offering an empty
| dropdown. Adding a store is adding a key here; no code changes.
|
| Within a store, each category has a "base" set applied to every type under
| it, plus the per-type tags. The review screen offers base + type,
| de-duplicated, with every tag pre-checked — unchecking is how you opt out.
|
| Tags are written exactly as they appear in Shopify (casing included), so
| adding one here never creates a near-duplicate of an existing tag.
|
| Shape, for reference while this is still being filled in:
|
|     'store.myshopify.com' => [
|         'Category Name' => [
|             'base'  => ['Tag on every type in this category'],
|             'types' => [
|                 'Type Name' => ['Tag', 'Another tag'],
|             ],
|         ],
|     ],
|
*/

return [

    // Bluesalon. Categories are added one at a time, each derived from that
    // category's own Shopify product export.
    'qatarbluesalon.myshopify.com' => [

        "Women's Fashion" => [

            /*
            | Only GCC, Women and Womens appear across clothing, shoes, bags and
            | accessories alike, so the clothing bucket tags (All Clothing,
            | Clothing, ClothingWomen, Women All Clothing, ...) live on each
            | clothing type instead: a pair of shoes must not be pushed
            | "All Clothing".
            |
            | Season, campaign and supplier tags in the export (new-season-2026,
            | Summer 2026, Ramadan*, EID*, SS22, AW21, Eid2 SS26, Gift Box,
            | Who: For Her, Sale, Special Prices, PROMOCEGID, FYFL, style codes)
            | are left out: they describe a promotion, not a product.
            */
            'base' => [
                'GCC',
                'Women',
                'Womens',
            ],

            'types' => [

                'Dresses' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'Dress',
                    'Dress Set',
                    'Dresses',
                    'Evening Dress',
                    'Knitted Dress',
                    'mcat: Women Clothing',
                    'Midi Dress',
                    'Mini Dress',
                    'Occasion Dresses',
                    'scat: Dresses',
                    'Scat: New In Women Clothing',
                    'Shirt Dress',
                    'Women All Clothing',
                    'Women All Clothing Dresses',
                    'Women Dresses',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Long Dresses' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'Dress',
                    'Dresses',
                    'Long Dress',
                    'mcat: Women Clothing',
                    'Occasion Dresses',
                    'scat: Dresses',
                    'Scat: New In Women Clothing',
                    'Women All Clothing',
                    'Women All Clothing Dresses',
                    'Women Dresses',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Gowns' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'Evening Dress',
                    'Gown',
                    'mcat: Women Clothing',
                    'Nightdress',
                    'Nightdresses',
                    'Nightdresses & Chemise',
                    'Occasion Dresses',
                    'scat: Gowns',
                    'Scat: New In Women Clothing',
                    'Women All Clothing',
                    'Women All Clothing Dresses',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Shirts & Blouses' => [
                    'All Clothing',
                    'Blouse',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'mcat: Women Clothing',
                    'Scat: New In Women Clothing',
                    'scat: Shirts & Blouses',
                    'Shirt',
                    'Shirts',
                    'Shirts & T-Shirts',
                    'Women All Clothing',
                    'Women All Clothing Shirts & Blouses',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Tops' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'Kimono',
                    'mcat: Women Clothing',
                    'Scat: New In Women Clothing',
                    'scat: Tops',
                    'Top',
                    'Tops',
                    'Tops & T-Shirts',
                    'Women All Clothing',
                    'Women All Clothing Tops',
                    'Women Top',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'T-Shirts' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'mcat: Women Clothing',
                    'Scat: New In Women Clothing',
                    'scat: T-Shirts',
                    'Shirts & T-Shirts',
                    'T-Shirt',
                    'T-Shirts',
                    'T-shirts',
                    'Tops & T-Shirts',
                    'Tshirt',
                    'Women All Clothing',
                    'Women T-Shirts',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Hoodies & Sweatshirts' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'Hoodie',
                    'Hoodies',
                    'Hoodies & Sweatshirt',
                    'mcat: Women Clothing',
                    'scat: Hoodies & Sweatshirt',
                    'Scat: New In Women Clothing',
                    'Sweater',
                    'Sweaters and Cardigans',
                    'Sweatshirt',
                    'Sweatshirt & Pants',
                    'Sweatshirts and Jackets',
                    'Women All Clothing',
                    'Women All Clothing Hoodies & Sweatshirts',
                    'Women hoodie',
                    'Women Sweatshirt',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Knitwear & Sweaters' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'Jersey',
                    'knitwear',
                    'mcat: Women Clothing',
                    'scat: Knitwear & Sweaters',
                    'Scat: New In Women Clothing',
                    'Shawl',
                    'Sweater',
                    'Sweaters and Cardigans',
                    'Sweaters and Jackets',
                    'Women All Clothing',
                    'Women Knitwear',
                    'Women Knitwear & sweater',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Cardigans' => [
                    'All Clothing',
                    'Cardigan',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'mcat: Women Clothing',
                    'scat: Cardigan And Coverups',
                    'Scat: New In Women Clothing',
                    'Sweaters and Cardigans',
                    'Women All Clothing',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Blazers' => [
                    'All Clothing',
                    'Blazer',
                    'Blazers',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'mcat: Women Clothing',
                    'scat: Blazers',
                    'Scat: New In Women Clothing',
                    'Women All Clothing',
                    'Women All Clothing Tailoring Coats & Jackets',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Coats & Jackets' => [
                    'All Clothing',
                    'Cape Blazer',
                    'Clothing',
                    'ClothingWomen',
                    'Coat',
                    'Coats & Jackets',
                    'Coats & jackets',
                    'Collection: Women Fashion',
                    'Jacket',
                    'Jackets',
                    'mcat: Women Clothing',
                    'scat: Coats & Jackets',
                    'Scat: New In Women Clothing',
                    'Vest',
                    'Vests',
                    'Women All Clothing',
                    'Women All Clothing Coats & Jackets',
                    'Women All Clothing Tailoring Coats & Jackets',
                    'women jacket',
                    'Women Jackets',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Trousers' => [
                    'All Clothing',
                    'Bottom',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'mcat: Women Clothing',
                    'Pant',
                    'Pants',
                    'Scat: New In Women Clothing',
                    'scat: Trousers',
                    'Trouser',
                    'Trousers',
                    'Trousers & Shorts',
                    'Women All Clothing',
                    'Women All Clothing Trousers',
                    'Women All Clothing Trousers Tailoring',
                    'Women Pant',
                    "Women's Fashion",
                    "Women's Pant",
                    'Womens Fashion',
                ],

                'Jeans' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'Denim',
                    'Jeans',
                    'mcat: Women Clothing',
                    'Pocket Jeans',
                    'scat: Jeans',
                    'Scat: New In Women Clothing',
                    'Women All Clothing',
                    'Women All Clothing Denim',
                    'Women Jeans',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Shorts' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'mcat: Women Clothing',
                    'Scat: New In Women Clothing',
                    'scat: Shorts',
                    'Short',
                    'Shorts',
                    'Trousers & Shorts',
                    'Women All Clothing',
                    'Women All Clothing Shorts',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Skirts' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'mcat: Women Clothing',
                    'Scat: New In Women Clothing',
                    'scat: Skirts',
                    'Skirt',
                    'skirt',
                    'Women All Clothing',
                    'Women All Clothing Skirts',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Jumpsuits' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'Jumpsuit',
                    'Jumpsuits',
                    'Jumpsuits & Playsuits',
                    'mcat: Women Clothing',
                    'Overall',
                    'Overalls',
                    'scat: Jumpsuits',
                    'Scat: New In Women Clothing',
                    'Women All Clothing',
                    'Women All Clothing Jumpsuits & Playsuits',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Sets' => [
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'mcat: Women Clothing',
                    'Scat: New In Women Clothing',
                    'scat: Sets',
                    'Set',
                    'Set Dress',
                    'Set Top & Trouser',
                    'Sets',
                    'Women All Clothing',
                    'Women All Clothing Tops Trousers',
                    'Women Sets',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Activewear' => [
                    'Activewear',
                    'All Clothing',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'Jogging Pants',
                    'Jogging suit',
                    'Jogging Suits',
                    'Jogging trouser',
                    'Jogging Trousers',
                    'mcat: Women Clothing',
                    'scat: Activewear',
                    'Scat: New In Women Clothing',
                    'Training Suit',
                    'Training Suits',
                    'Women All Clothing',
                    'Women All Clothing Training Suits',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Kaftans & Abayas' => [
                    'Abaya',
                    'All Clothing',
                    'Caftan',
                    'Clothing',
                    'ClothingWomen',
                    'Collection: Women Fashion',
                    'Jalabiya',
                    'Kaftan',
                    'Kaftan Set',
                    'Kaftans & Abayas',
                    'mcat: Women Clothing',
                    'scat: Abayas And Kaftans',
                    'Scat: New In Abayas and Kaftans',
                    'Scat: New In Women Clothing',
                    'Traditional Wear',
                    'Women All Clothing',
                    'Women All Clothing Traditional Wear Ramadan Edit',
                    "Women's Fashion",
                    'Womens Fashion',
                ],

                'Scarves' => [
                    'Accessories',
                    'All Accessories',
                    'Collection: Women Fashion',
                    'Ladies Scarf',
                    'Scarf',
                    'Scarves',
                    'scat: Scarves',
                    'Women All Accessories',
                    'Womenall Accessories Scarves',
                ],

                'Belts' => [
                    'Accessories',
                    'All Accessories',
                    'Belt',
                    'Belts',
                    'scat: Belt',
                    "Women's Belt",
                ],

                'Hats & Caps' => [
                    'Accessories',
                    'All Accessories',
                    'Cap',
                    'Hat',
                    'Hats',
                    "Women's Hats",
                ],

                'Gloves' => [
                    'Gloves',
                    'Women Gloves',
                ],

                'Socks' => [
                    'Accessories',
                    'All Accessories',
                    'Socks',
                ],

                'Brooches' => [
                    'Accessories',
                    'All Accessories',
                    'Brooch',
                    'Collection: Accessories',
                    'Collection: Women Fashion',
                ],

                'Sneakers' => [
                    'All Shoes',
                    'Casual',
                    'Collection: Footwear',
                    'Espadrilles',
                    'Footwear',
                    'Runners',
                    'Scat: New In Women Footwear',
                    'scat: Sneakers',
                    'scat: Sneakers & trainers',
                    'Shoes',
                    'Sneaker',
                    'Sneakers',
                    'Trainers',
                    'Women All Clothing Trainers',
                    'women all shoes',
                    'Women All Shoes Trainers',
                    "women's Shoe",
                ],

                'Heels' => [
                    'All Shoes',
                    'Collection: Footwear',
                    'Footwear',
                    'Heels',
                    'Pumps',
                    'Scat: New In Women Footwear',
                    'scat: Pumps & heels',
                    'Shoes',
                    'Slingback',
                    'women all shoes',
                    'Women All Shoes Heels',
                    "women's Shoe",
                ],

                'Flats & Ballets' => [
                    'All Shoes',
                    'Ballet Shoes',
                    'Ballets',
                    'Collection: Footwear',
                    'Footwear',
                    'scat: Ballet & flats',
                    'Scat: New In Women Footwear',
                    'Shoes',
                    'Skimmer',
                    'women all shoes',
                    'Women All Shoes Flats',
                    "women's Shoe",
                ],

                'Loafers' => [
                    'All Shoes',
                    'Collection: Footwear',
                    'Driver',
                    'Drivers',
                    'Footwear',
                    'Loafer',
                    'Loafers',
                    'scat: Loafers',
                    'Scat: New In Women Footwear',
                    'Shoes',
                    'Slip On',
                    'women all shoes',
                    'Women All Shoes Flats Loafers',
                    'Women All Shoes Loafers',
                    "women's Shoe",
                ],

                'Oxford Shoes' => [
                    'All Shoes',
                    'Collection: Footwear',
                    'Footwear',
                    'Oxford',
                    'Oxford Shoes',
                    'Scat: New In Women Footwear',
                    'scat: Oxford Shoes',
                    'Shoes',
                    'women all shoes',
                    'Women All Shoes Brogues & Oxfords',
                    "women's Shoe",
                ],

                'Sandals' => [
                    'All Shoes',
                    'Collection: Footwear',
                    'Footwear',
                    'Sandal',
                    'Sandals',
                    'Scat: New In Women Footwear',
                    'scat: Sandals',
                    'Shoes',
                    'Slide',
                    'Slide Sandals',
                    'Slides',
                    'Slides & Sandals',
                    'women all shoes',
                    'Women All Shoes Sandals',
                    "women's Shoe",
                ],

                'Wedges' => [
                    'All Shoes',
                    'Collection: Footwear',
                    'Footwear',
                    'Scat: New In Women Footwear',
                    'Shoes',
                    'Wedge',
                    'Wedge Sandals',
                    'Wedges',
                    'women all shoes',
                    'Women All Shoes Heels',
                    'Women All Wedges',
                    "women's Shoe",
                ],

                'Mules' => [
                    'All Shoes',
                    'Collection: Footwear',
                    'Footwear',
                    'Mule',
                    'scat: Mules',
                    'Scat: New In Women Footwear',
                    'Shoes',
                    'women all shoes',
                    'Women All Shoes Mules',
                    "women's Shoe",
                ],

                'Slippers' => [
                    'All Shoes',
                    'Collection: Footwear',
                    'Footwear',
                    'Scat: New In Women Footwear',
                    'scat: Slippers',
                    'Shoes',
                    'Slippers',
                    'women all shoes',
                    'Women All Shoes Slippers',
                    "women's Shoe",
                ],

                'Boots' => [
                    'All Shoes',
                    'Bootie',
                    'Booties',
                    'Boots',
                    'Collection: Footwear',
                    'Footwear',
                    'Scat: New In Women Footwear',
                    'Shoes',
                    'women all shoes',
                    'Women All Shoes Boots',
                    "women's Shoe",
                ],

                'Handbags' => [
                    'All Bags',
                    'All Other Bags',
                    'Bag',
                    'Bags',
                    'Hand Bag',
                    'Handbag',
                    'Handbags',
                    'Shoulder Bag',
                    'Shoulder Strap',
                    'Women All Bags',
                ],

                'Tote Bags' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'scat: Tote Bag',
                    'Tote Bag',
                    'Women All Bags',
                ],

                'Crossbody Bags' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'Crossbody Bag',
                    'Women All Bags',
                    'Women Cross-body Bags',
                ],

                'Clutches' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'Clutch',
                    'Clutch Bag',
                    'Cluth Bag',
                    'scat: Mini Bags',
                    'Women All Bags',
                    'Women Mini Bag',
                ],

                'Backpacks' => [
                    'All Bags',
                    'Backpack',
                    'Backpack Bag',
                    'Bag',
                    'Bags',
                    'Women All Bags',
                    'Women Backpack',
                ],

                'Wallets' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'Wallet',
                    'Wallet & Cardholders',
                    'Wallets',
                    'Wallets & Card Holder',
                    'Women All Bags',
                    'Women Wallet',
                ],

                'Pouches' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'Pouch',
                    'SLG',
                    'Women All Bags',
                ],

            ],
        ],

        "Men's Fashion" => [

            /*
            | Men, Mens and GCC are the only tags this department puts on
            | (nearly) every row. The top-level bucket tag splits three ways
            | (All Clothing / All Accessories / All Shoes) and "Our Exclusives"
            | is missing from a few brands, so both live on the types.
            |
            | Campaign tags in the export (EID2023, Father's day, Last Chance,
            | Special Prices, SP) are deliberately left out: they describe a
            | promotion, not a product, and would be pushed onto new SKUs long
            | after the promotion ended.
            */
            'base' => [
                'GCC',
                'Men',
                'Mens',
            ],

            'types' => [

                'Polo Shirts' => [
                    'All Clothing',
                    "Men's Polo Shirt",
                    'Mens Fashion',
                    'Polo',
                    'Polo shirt',
                    'Polo T-shirt',
                    'Scat: New In Men Clothing',
                    'scat: Polo shirts',
                    'Shirts & T-Shirts',
                ],

                'Shirts' => [
                    'All Clothing',
                    'Men Shirts',
                    'Mens Fashion',
                    'Scat: New In Men Clothing',
                    'scat: Shirts',
                    'Shirt',
                    'Shirts',
                    'Shirts & T-Shirts',
                ],

                'T-Shirts' => [
                    'All Clothing',
                    'Men T-shirts',
                    'Mens Fashion',
                    'scat: T-Shirts',
                    'Shirts & T-Shirts',
                    'T-shirt',
                    'T-Shirt',
                    'T-Shirts',
                    'T. shirt',
                    'T.Shirt',
                    'T.shirt',
                    'Top',
                    'Tops',
                    'Tops & T-Shirts',
                    'Tshirt',
                ],

                'Sweaters & Cardigans' => [
                    'All Clothing',
                    'Cardigan',
                    'knitwear',
                    'Men sweater',
                    'Men Sweatshirt',
                    'Mens Fashion',
                    'Our Exclusives',
                    'Pullover',
                    'scat: sweaters and cardigans',
                    'Sweater',
                    'Sweaters & cardigans',
                    'Sweaters and Cardigans',
                    'Sweaters and Jackets',
                    'Sweatknit',
                    'Sweatshirts and Jackets',
                ],

                'Sweatshirts & Hoodies' => [
                    'All Clothing',
                    'Hoodies',
                    'Hoodies & Sweatshirt',
                    'Hoody',
                    'Men Hoodies',
                    'Men Sweatshirt',
                    'Men Sweatshirt & Hoodies',
                    'Mens Fashion',
                    'Scat: New In Men Clothing',
                    'scat: Sweatshirts & hoodies',
                    'Sweat jacket',
                    'Sweater',
                    'Sweatknit',
                    'Sweatshirt',
                    'Sweatshirts and Jackets',
                ],

                'Pullovers' => [
                    'Pullover',
                    'pullover',
                ],

                'Coats & Jackets' => [
                    'All Clothing',
                    'Clothing',
                    'Coat',
                    'Coats & Jackets',
                    'Jacket',
                    'jacket',
                    'Jackets',
                    'Jaket',
                    'Men Jackets',
                    'Mens Fashion',
                    'Our Exclusives',
                    'scat: Jackets & coats',
                    'Sports Jacket',
                    'Sports Jackets',
                    'Vest',
                ],

                'Trousers' => [
                    'All Clothing',
                    'Men Trousers',
                    'Mens Fashion',
                    'Pant',
                    'Pants',
                    'scat: Trousers',
                    'scat: Trousers & shorts',
                    'Trouser',
                    'Trousers',
                    'Trousers & Shorts',
                    'trousers for men',
                ],

                'Shorts' => [
                    'All Clothing',
                    'Men Shorts',
                    'Mens Fashion',
                    'Scat: New In Men Clothing',
                    'scat: Shorts',
                    'scat: Trousers & shorts',
                    'Short',
                    'Shorts',
                    'Trousers & Shorts',
                ],

                'Jeans' => [
                    'All Clothing',
                    'Clothing',
                    'Denim',
                    'Jeans',
                    'Men Jeans Pants',
                    'Mens Fashion',
                    'Pocket Jeans',
                    'scat: Jeans',
                    'scat: Trousers',
                    'scat: Trousers & shorts',
                    'Trouser',
                    'Trousers',
                    'Trousers & Shorts',
                ],

                'Sportswear' => [
                    'Activewear',
                    'All Clothing',
                    'Mens Fashion',
                    'Our Exclusives',
                    'scat: Sportswear',
                    'Sportswear',
                ],

                'Caps & Hats' => [
                    'Accessories',
                    'All Accessories',
                    'BASIC',
                    'Basics',
                    'Bonet',
                    'Cap',
                    'Hat',
                    'Hats',
                    'Men Caps and Hats',
                    'Mens Fashion',
                    'MF Accessories',
                    'Mf Accessories',
                    'Our Exclusives',
                    'scat: Caps & hats',
                ],

                'Scarves' => [
                    'Accessories',
                    'All Accessories',
                    'Men Scarf',
                    'Mens Fashion',
                    'Mf Accessories',
                    'MF Accessories',
                    'Our Exclusives',
                    'scarf',
                    'Scarves',
                    'scat: Scarves',
                ],

                'Belts' => [
                    'Accessories',
                    'All Accessories',
                    'Belt',
                    'Belts',
                    'Men All Accessories',
                    'Men Belts',
                    "Men's All Accessories",
                    'Mens Fashion',
                    'MF Accessories',
                    'Mf Accessories',
                    'Our Exclusives',
                ],

                'Ties & Bowties' => [
                    'Accessories',
                    'All Accessories',
                    'BASIC',
                    'Basics',
                    'Men All Accessories',
                    "Men's All Accessories",
                    'Mens Fashion',
                    'Mf Accessories',
                    'Our Exclusives',
                    'scat: Ties & bowties',
                    'Ties',
                ],

                'Sneakers' => [
                    'All Shoes',
                    'All ShoesOur Exclusives',
                    'Footwear',
                    'Men All Shoes Shoes',
                    'Men Sneaker',
                    'Mens Fashion',
                    'Our Exclusives',
                    'Scat: new In Men Footwear',
                    'scat: Sneakers',
                    'Shoes',
                    'Sneaker',
                    'Sneakers',
                    'Trainers',
                ],

                'Boots' => [
                    'All Shoes',
                    'Bootie',
                    'Booties',
                    'Boots',
                    'Footwear',
                    'Men All Shoes Boots',
                    'Mens Boots',
                    'Mens Fashion',
                    'Our Exclusives',
                ],

                'Oxford Shoes' => [
                    'All Shoes',
                    'Our Exclusives',
                    'Oxford',
                    'Oxford Shoes',
                    'Scat: new In Men Footwear',
                    'scat: Oxford Shoes',
                ],

                'Shoes' => [
                    'All Shoes',
                    'All ShoesOur Exclusives',
                    'Footwear',
                    'Men All Shoes Shoes',
                    'Mens Fashion',
                    'Our Exclusives',
                    'Shoes',
                ],

                'Suits' => [
                    'All Clothing',
                    "Men's Suit",
                    'Mens Fashion',
                    'Our Exclusives',
                    'Suit',
                    'Suits',
                ],

                'Blazers' => [
                    'All Clothing',
                    'Blazer',
                    "Men's Blazer",
                    'Mens Fashion',
                    'Our Exclusives',
                    'scat: Blazers',
                ],

                'Underwear' => [
                    'Accessories',
                    'All Clothing',
                    'Basics',
                    'Boxer',
                    'Brif',
                    'Clothing',
                    'Men Underwear',
                    'Mens Fashion',
                    'Mf Accessories',
                    'Our Exclusives',
                    'scat: Underwear',
                    'Tank',
                    'Underwear',
                    'Underwear Set',
                ],

                'Socks' => [
                    'Accessories',
                    'All Accessories',
                    'All Clothing',
                    'Basics',
                    'Men All Accessories',
                    'Mens Fashion',
                    'MF Accessories',
                    'Mf Accessories',
                    'scat: Socks',
                    'Socks',
                ],

                'Swimwear' => [
                    'All Clothing',
                    'Beachwear',
                    'Men Shorts',
                    'Mens Fashion',
                    'Short',
                    'Shorts',
                    'Swim short',
                    'Swimsuit',
                    'Swimsuits',
                    'Swimwear',
                    'Trousers & Shorts',
                ],

                'Sleepwear' => [
                    'All Clothing',
                    'Loungewear',
                    'Mens Fashion',
                    'Nightwear',
                    'Nightwear & Underwear',
                    'Our Exclusives',
                    'Pyjama',
                    'Pyjamas',
                    'Pyjamas & Loungewear',
                    'Robe',
                    'scat: Nightwear & loungewear',
                    'Sleepwear',
                    'Sleepwear & Loungewear',
                    'Sleepwear and Loungewear',
                ],

                'Training Suits' => [
                    'All Clothing',
                    'Jogger Suit',
                    'Jogging Pants',
                    'Jogging suit',
                    'Jogging Suits',
                    'Jogging trouser',
                    'Jogging Trouser',
                    'Jogging Trousers',
                    'Men Jogging Pants',
                    'Mens Fashion',
                    'Sportswear',
                    'Training suit',
                    'Training Suit',
                    'Trousers & Shorts',
                ],

                'Traditional Wear' => [
                    'All Clothing',
                    'Our Exclusives',
                    'Traditional Wear',
                ],

                'Wallets' => [
                    'Accessories',
                    'All Accessories',
                    'All Bags',
                    'All Bags-Our Exclusives',
                    'Card Holder',
                    'Credit Card Holder',
                    'Lifestyle Accessories',
                    'Men All bags',
                    'Men Wallet',
                    "Men's All Accessories",
                    'Mens Fashion',
                    'MF Accessories',
                    'Our Exclusives',
                    'scat: Wallets & cardholders',
                    'Wallet',
                    'Wallet & Cardholders',
                    'Wallets',
                    'Wallets & Card Holder',
                ],

                'Bags' => [
                    'Accessories',
                    'All Bags',
                    'All Other Bags',
                    'Backpacks',
                    'Bag',
                    'Bags',
                    'Crossover',
                    'Men All bags',
                    'Men Handbag',
                    'MF Accessories',
                    'Our Exclusives',
                    'Scat: New In Bags & Accessories',
                ],

                'Sunglasses' => [
                    'Accessories',
                    'All Accessories',
                    'Men All Accessories',
                    'Men Sunglasses',
                    "Men's All Accessories",
                    'Mens Fashion',
                    'Mf Accessories',
                    'Our Exclusives',
                    'scat: Sunglasses',
                    'Sunglasses',
                ],

                'Arabic Sandals' => [
                    'All Shoes',
                    'Arabic Sandal',
                    'Footwear',
                    'Men  Sandals',
                    'Mens',
                    'Our Exclusives',
                    'Sandal',
                    'Sandals',
                    'Scat: new In Men Footwear',
                    'Scat: New In Mens Traditional Footwear',
                    'scat: Traditional Footwear',
                    'Slide Sandals',
                    'Slides & Sandals',
                    'Traditional Footwear',
                ],

                'Slides & Sandals' => [
                    'All Shoes',
                    'Footwear',
                    'Men All Shoes Slipper',
                    'Men All Shoes slippers',
                    'Mens',
                    'Our Exclusives',
                    'Sandals',
                    'scat: Slides & sandals',
                    'Slide',
                    'Slide Sandals',
                    'Slides',
                    'Slides & Sandals',
                    'Slippers',
                    'Traditional Footwear',
                ],

                'Loafers' => [
                    'All Shoes',
                    'All ShoesOur Exclusives',
                    'Drivers',
                    'Loafer',
                    'Loafers',
                    'Men All Shoes Shoes',
                    'Our Exclusives',
                    'scat: Loafers & drivers',
                    'Shoes',
                    'Slip On',
                ],

                'Gloves' => [
                    'Accessories',
                    'All Accessories',
                    'Gloves',
                    'MF Accessories',
                ],

                'Key Holders' => [
                    'All Accessories',
                    'Key Holder',
                    'Mf Accessories',
                ],

                'Backpacks' => [
                    'All Bags',
                    'All Bags-Our Exclusives',
                    'All Other Bags',
                    'Backpack',
                    'Backpack Bag',
                    'Backpacks',
                    'Casual Backpack',
                    'Men All bags',
                    'Men Backpack',
                    'Our Exclusives',
                ],

                'Crossbody & Shoulder Bags' => [
                    'All Bags',
                    'All Other Bags',
                    'Bag',
                    'Bags',
                    'Cross Body Bag',
                    'Crossbody',
                    'Crossbody Bag',
                    'Crossover',
                    'Men All bags',
                    'Men Crossbag',
                    'Men Crossbody bags',
                    'Our Exclusives',
                    'scat: Crossbody bags',
                    'Shoulder Bag',
                    'Waist Bag',
                ],

                'Pouches' => [
                    'All Bags',
                    'All Bags-Our Exclusives',
                    'Bag',
                    'Bags',
                    'Clutch Bag',
                    'Cosmetic Bag',
                    'Men All bags',
                    'Pouch',
                    'Toiletry Bag',
                    'Travel Pouch',
                    'Zip Pouch',
                ],

                'Luggage & Travel Bags' => [
                    'Attaches',
                    'Briefcase',
                    'Lugagge & Holdalls',
                    'Luggage & Travel',
                    'Travel Accessories',
                    'Travel Series',
                    'Trolley 3 P.C',
                ],

            ],
        ],

        'Luggage' => [

            /*
            | Nothing is shared by every product (suitcases carry "Luggage",
            | bags carry "All Bags", accessories carry "Accessories"), so each
            | type carries its own set.
            |
            | Left out: brand tags (Samsonite, American tourister, Hedgren,
            | Pacsafe, Briggs & Riley, Nexis, Porsche Design ...), SKU/style codes
            | (UT0 (*) 09, KT4 (*) 009, HED207...), and campaign tags
            | (PROMOCEGID, EID2023, departure-to-desk, new-season-2025, BTS2021,
            | BOGOFX, Spring Festival, Sale, New Arrival ...).
            */
            'base' => [],

            'types' => [

                'Hard Luggage' => [
                    'Cabin/Small',
                    'Carry-On',
                    'Check-In',
                    'extra-large-size',
                    'Hard Luggage',
                    'Hard-Soft-Luggage',
                    'large-size',
                    'Luggage',
                    'Luggage & Travel',
                    'Luggage Hard',
                    'medium-size',
                    'scat: Cabin',
                    'scat: Extra Large Luggage',
                    'scat: Hard Luggage',
                    'scat: Large Luggage',
                    'scat: Medium Luggage',
                    'Scat: New In Luggage',
                    'small-size',
                    'View All Luggage',
                ],

                'Soft Luggage' => [
                    'Cabin/Small',
                    'Carry-On',
                    'Check-In',
                    'Hard-Soft-Luggage',
                    'large-size',
                    'Luggage',
                    'Luggage & Travel',
                    'Luggage Soft',
                    'medium-size',
                    'scat: Cabin',
                    'scat: Large Luggage',
                    'scat: Medium Luggage',
                    'Scat: New In Luggage',
                    'scat: Soft Luggage',
                    'small-size',
                    'Soft Luggage',
                    'View All Luggage',
                ],

                'Backpacks' => [
                    'All Bags',
                    'Backpack',
                    'Backpack Bag',
                    'Backpacks',
                    'Bag',
                    'Bags',
                    'Business Backpack',
                    'Casual Backpack',
                    'Laptop Backpack',
                    'Luggage Bags',
                    'Luggage Bags Backpacks',
                    'Men All bags',
                    'Men Backpack',
                    'scat: Backpacks',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'Women All Bags',
                    'Women Backpack',
                ],

                'School Backpacks' => [
                    'Backpack',
                    'Bag',
                    'Luggage Bags',
                    'Luggage Bags School Backpacks',
                    'scat: Backpacks',
                    'Scat: New In Luggage',
                    'scat: School Backpacks',
                ],

                'Laptop Bags & Briefcases' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'Bailhandle',
                    'Briefcase',
                    'Expandable Brief',
                    'Laptop Bag',
                    'Laptop Bags',
                    'Laptop Briefcase',
                    'Luggage Bags',
                    'Luggage Bags Bailhandle',
                    'mcat: Laptop Bags & Briefcases',
                    'Men All bags',
                    'scat: Bailhandle',
                    'scat: Laptop bags & briefcases',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'Women All Bags',
                ],

                'Crossbody Bags' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'Cross Body Bag',
                    'Cross Over',
                    'Crossbody',
                    'Crossbody Bag',
                    'Crossbodys',
                    'Crossover',
                    'Crossover Bag',
                    'Luggage Bags',
                    'Luggage Bags Crossbody',
                    'Men All bags',
                    'Men Crossbag',
                    'Men Crossbody bags',
                    'scat: Crossbody',
                    'scat: Crossbody bags',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'Women All Bags',
                    'Women Cross-body Bags',
                ],

                'Sling Bags' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'Luggage Bags',
                    'Men All bags',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'SLING BAG',
                    'Sling Pack',
                    'Slingback',
                    'Slingbag',
                    'Women All Bags',
                ],

                'Shoulder Bags' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'Luggage Bags',
                    'Luggage Bags Crossbody',
                    'Men All bags',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'Shoulder Bag',
                    'Women All Bags',
                ],

                'Messenger Bags' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'Luggage Bags',
                    'Luggage Bags Crossbody',
                    'Men All bags',
                    'Messenger Bag',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'Women All Bags',
                ],

                'Duffel Bags' => [
                    'All Bags',
                    'All Other Bags',
                    'Bag',
                    'Bags',
                    'Duffel Bag',
                    'Duffel Bags',
                    'Duffle',
                    'Duffle Bag',
                    'Luggage Bags',
                    'Luggage Bags Other  Bags',
                    'Men All bags',
                    'Normal Duffel',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'Weekend Bag',
                    'Weekender Traveller Bag',
                    'Women All Bags',
                ],

                'Tote Bags' => [
                    'All Bags',
                    'All Other Bags',
                    'Bag',
                    'Bags',
                    'Luggage Bags',
                    'Luggage Bags Other  Bags',
                    'Men All bags',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'scat: Tote Bag',
                    'Tote',
                    'Tote Bag',
                    'Totes',
                    'Women All Bags',
                ],

                'Clutch Bags' => [
                    'All Bags',
                    'Bag',
                    'Bags',
                    'Clutch',
                    'Clutch Bag',
                    'Cluth Bag',
                    'Luggage Bags',
                    'Men All bags',
                    'scat: Clutch Bag',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'Women All Bags',
                ],

                'Handbags' => [
                    'All Bags',
                    'All Other Bags',
                    'Bag',
                    'Bags',
                    'Hand Bag',
                    'Handbag',
                    'Handbags',
                    'Luggage Bags',
                    'Luggage Bags Other  Bags',
                    'Men All bags',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'Women All Bags',
                ],

                'Waist Bags' => [
                    'All Bags',
                    'All Other Bags',
                    'Bag',
                    'Bags',
                    'Belt Bag',
                    'Luggage Bags',
                    'Luggage Bags Other  Bags',
                    'Men All bags',
                    'Scat: New In Bags & Accessories',
                    'Scat: New In Luggage',
                    'Waist Bag',
                    'Women All Bags',
                ],

                'Garment Bags' => [
                    'Garment Bag',
                    'Luggage Bags Other  Bags',
                    'Scat: New In Luggage',
                ],

                'Toiletry & Cosmetic Bags' => [
                    'Accessories',
                    'All Bags',
                    'Beauty Case',
                    'Cosmetic Bag',
                    'Cosmetic Case',
                    'Cosmetics and Toiletries',
                    'Luggage Travel Accessories',
                    'Luggage Travel Accessories Other Travel Accessories',
                    'Luggage Travel Accessories Toiletries',
                    'Scat: New In Luggage',
                    'scat: Toiletries',
                    'Toiletries Bag',
                    'Toiletry Bag',
                    'Toiletry Case',
                    'Toiletry Kit',
                ],

                'Wallets' => [
                    'Accessories',
                    'Bi-Fold Wallet',
                    'Bifold Wallet',
                    'Ladies Wallet',
                    'Luggage Travel Accessories Ladies Wallets',
                    'Luggage Travel Accessories Men Wallets',
                    'Luggage Travel Accessories Wallets',
                    'Men Wallet',
                    "Men's All Accessories",
                    'Scat: New In Luggage',
                    'scat: Wallets & cardholders',
                    'Travel Wallet',
                    'Wallet',
                    'Wallet & Cardholders',
                    'Wallets',
                    'Wallets & Card Holder',
                    'Women Wallet',
                ],

                'Card Holders' => [
                    'Accessories',
                    'Card Case',
                    'Card Case Wallet',
                    'Card Holder',
                    'Credit Card Holder',
                    'Scat: New In Luggage',
                    'Wallet & Cardholders',
                    'Wallets & Card Holder',
                ],

                'Belts' => [
                    'Accessories',
                    'Belt',
                    'Belts',
                    'Men All Accessories',
                    'Men Belts',
                    'Mens',
                    'Scat: New In Luggage',
                ],

                'Travel Pouches' => [
                    'Accessories',
                    'All Bags',
                    'Luggage Travel Accessories',
                    'Luggage Travel Accessories Other Travel Accessories',
                    'Neck Pouch',
                    'Pouch',
                    'Pouch-Rfid',
                    'Scat: New In Luggage',
                    'Travel Pouch',
                ],

                'Luggage Covers' => [
                    'Accessories',
                    'Accessories type',
                    'Luggage Cover',
                    'Luggage cover',
                    'Luggage Travel Accessories',
                    'Luggage Travel Accessories Other Travel Accessories',
                    'Scat: New In Luggage',
                    'Travel friendly',
                ],

                'Luggage Tags' => [
                    'Accessories',
                    'Accessories type',
                    'Luggage Tag',
                    'Scat: New In Luggage',
                    'Travel friendly',
                ],

                'Luggage Straps' => [
                    'Accessories',
                    'Accessories type',
                    'Luggage Strap',
                    'Scat: New In Luggage',
                    'Travel friendly',
                ],

                'Packing Organizers' => [
                    'Accessories',
                    'All Bags',
                    'packing cubes',
                    'Packing solution',
                    'Packing Solutions',
                    'Scat: New In Luggage',
                    'Travel friendly',
                ],

                'Travel Pillows' => [
                    'Accessories',
                    'Inflat Pillow',
                    'Luggage Travel Accessories',
                    'Luggage Travel Accessories Other Travel Accessories',
                    'Memory Foam Pillow',
                    'Neck Pillow',
                    'Pillow',
                    'Scat: New In Luggage',
                    'Travel Pillow',
                ],

                'Travel Locks' => [
                    'Accessories',
                    'Combi Lock',
                    'Combilock',
                    'Luggage Travel Accessories',
                    'Luggage Travel Accessories Other Travel Accessories',
                    'Metal Lock',
                    'Scat: New In Luggage',
                    'Travel Key Lock',
                    'TSA Lock',
                    'Tsa Metal Lock',
                ],

                'Chargers & USB' => [
                    'Accessories',
                    'Charger',
                    'Luggage Travel Accessories',
                    'Luggage Travel Accessories Charger & USB',
                    'Luggage Travel Accessories Other Travel Accessories',
                    'Power Bank',
                    'scat: Charger & USB',
                    'Scat: New In Luggage',
                ],

                'Laptop & Tablet Covers' => [
                    'Accessories',
                    'Luggage Travel Accessories',
                    'Luggage Travel Accessories Notebook & Laptop Covers',
                    'Luggage Travel Accessories Other Travel Accessories',
                    'Notebook Cover',
                    'Scat: New In Luggage',
                    'Tablet - Notebook Cover',
                ],

                'Passport Covers' => [
                    'Accessories',
                    'Luggage Travel Accessories',
                    'Luggage Travel Accessories Other Travel Accessories',
                    'Passport Cover',
                    'Passport Holder',
                    'Scat: New In Luggage',
                ],

            ],
        ],

        'Watches' => [

            /*
            | Nothing is shared store-wide here: this export's "Watches" type is
            | the watches & jewellery department, so it also carries pens,
            | wallets and cufflinks, and the men's and women's tag sets have no
            | tag in common. Everything therefore lives on the type.
            */
            'base' => [],

            'types' => [

                "Men's Fashion Watches" => [
                    'Collection: Watches',
                    'Fashion Watches',
                    'Men',
                    'Mens',
                    'Mens Watches',
                    'scat: Fashion Timepieces',
                    'Scat: New In Mens Watches',
                    'Watch',
                    'Watches',
                ],

                "Men's Luxury Watches" => [
                    'Collection: Watches',
                    'Luxury Watches',
                    'Men',
                    'Mens',
                    'Mens Watches',
                    'scat: Luxury Timepieces',
                    'Scat: New In Mens Watches',
                    'Watch',
                    'Watches',
                ],

                "Women's Fashion Watches" => [
                    'Collection: Watches',
                    'Fashion Watches',
                    'scat: Fashion Timepieces',
                    'Scat: New In Women Watches',
                    'Watch',
                    'Watches',
                    'Women',
                    'Women Watches & jewellery',
                    'Womens',
                    'Womens Watches',
                ],

                'Watch Sets' => [
                    'Collection: Watches',
                    'Fashion Watches',
                    'Men',
                    'Mens',
                    'Mens Watches',
                    'scat: Fashion Timepieces',
                    'Scat: New In Mens Watches',
                    'Watch',
                    'Watch Set',
                    'Watches',
                ],

                'Bracelets' => [
                    'Fashion Jewellery',
                    'Ladies bracelet',
                    'scat: Bracelets',
                    'scat: Fashion Jewellery',
                    'Scat: New In Women Jewellery',
                    'Women',
                    'Women Watches & jewellery',
                    "Women's Jewellery",
                    'Womens',
                ],

                'Bangles' => [
                    'Bangle',
                    'Fashion Jewellery',
                    'Ladies bracelet',
                    'scat: Bracelets',
                    'scat: Fashion Jewellery',
                    'Scat: New In Women Jewellery',
                    'Women',
                    'Women Watches & jewellery',
                    "Women's Jewellery",
                    'Womens',
                ],

                'Necklaces' => [
                    'Fashion Jewellery',
                    'Necklace',
                    'Necklace With Pendant',
                    'scat: Fashion Jewellery',
                    'scat: Necklaces',
                    'Scat: New In Women Jewellery',
                    'Women',
                    'Women Necklaces',
                    'Women Watches & jewellery',
                    "Women's Jewellery",
                    'Womens',
                ],

                'Cufflinks' => [
                    'Cufflink',
                    'Cufflinks',
                    'Men',
                    'Men All Accessories',
                    "Men's All Accessories",
                    'Mens',
                    'scat: Cufflinks',
                ],

                'Wallets & Cardholders' => [
                    'Men',
                    'Men All Accessories',
                    'Men Wallet',
                    "Men's All Accessories",
                    'Mens',
                    'scat: Wallets & cardholders',
                    'Wallet & Cardholders',
                    'Wallets & Card Holder',
                ],

                'Pens' => [
                    'Men',
                    'Men All Accessories',
                    "Men's All Accessories",
                    'Mens',
                    'Pen',
                    'scat: Pens',
                ],

            ],
        ],

        'Perfumes & Cosmetics' => [

            /*
            | No tag is shared across this category either: a mainstream
            | women's fragrance, a niche gift set and a box of agarwood have
            | nothing in common in this export, so each type carries its own
            | full set.
            */
            'base' => [],

            'types' => [

                "Women's Fragrances" => [
                    'Beauty Fragrances',
                    'Beauty Fragrances Fragrance',
                    'Beauty Women fragrances',
                    'Fragrance',
                    'Fragrances & Cosmetics',
                    'scat: Fragrance',
                    'Scat: New In Beauty & fragrance',
                    'scat: Women Fragrance',
                    'Women',
                    "Women'S Fragrance",
                ],

                "Men's Fragrances" => [
                    'Beauty Fragrances',
                    'Beauty Fragrances Fragrance',
                    'Beauty Men fragrances',
                    'Fragrance',
                    'Fragrances & Cosmetics',
                    "Men'S Fragrances",
                    'Mens',
                    'scat: Fragrance',
                    'scat: Men Fragrance',
                    'Scat: New In Beauty & fragrance',
                ],

                'Niche Fragrances' => [
                    'Beauty',
                    'Beauty Niche Fragrances',
                    'Beauty Niche fragrances Fragrance',
                    'Niche fragrances',
                    'Niche Perfumery',
                    'scat: Fragrance',
                    'Scat: New In Beauty & fragrance',
                    'scat: Niche Fragrances',
                ],

                'Fragrance Gift Sets' => [
                    'Beauty Fragrances',
                    'Beauty Fragrances Fragrance',
                    'Beauty Fragrances Gift Set',
                    'Fragrance',
                    'Fragrances',
                    'Fragrances & Cosmetics',
                    'Gift',
                    'Gift Set',
                    'scat: Fragrance',
                    'scat: Gift Set',
                    'Scat: New In Beauty & fragrance',
                ],

                'Niche Gift Sets' => [
                    'Beauty Niche Fragrances',
                    'Beauty Niche fragrances Gift Set',
                    'Niche fragrances',
                    'Niche Perfumery',
                    'scat: Gift Set',
                    'Scat: New In Beauty & fragrance',
                    'scat: Niche Fragrances',
                ],

                'Body Lotion' => [
                    'Beauty',
                    'Beauty Niche Bathline',
                    'Beauty Niche fragrances Bathline',
                    'Body Lotion',
                    'Niche fragrances',
                    'Niche Perfumery',
                    'Scat: New In Beauty & fragrance',
                    'scat: Niche Bathline',
                ],

                'Hand Cream' => [
                    'Beauty',
                    'Beauty Niche Bathline',
                    'Beauty Niche fragrances Bathline',
                    'Hand Cream',
                    'Niche Perfumery',
                    'Scat: New In Beauty & fragrance',
                    'scat: Niche Bathline',
                ],

                'Home Fragrance' => [
                    'All home fragrance',
                    'Beauty',
                    'Beauty Fragrancess Home fragrance',
                    'Beauty Niche fragrances Home Fragrance',
                    'Niche fragrances',
                    'Scat: New In Beauty & fragrance',
                    'scat: Niche Home Fragrance',
                ],

            ],
        ],

        'Make Up & Skin Care' => [

            /*
            | 'Beauty' is the one tag this export puts on nearly every row, so
            | it is the base; everything else splits between cosmetics, skin
            | care and hair care, which share nothing else.
            */
            'base' => [
                'Beauty',
            ],

            'types' => [

                'Lipsticks' => [
                    'Beauty Cosmetics',
                    'Beauty Cosmetics Lips',
                    'Beauty Lips',
                    'Lips',
                    'Lipstick',
                    'Liquid Lipstick',
                    'Makeup',
                    'scat: Lipsticks',
                ],

                'Foundation' => [
                    'Beauty Cosmetics',
                    'Beauty Cosmetics Face',
                    'Beauty Selfcare Skincare',
                    'Foundation',
                    'Make Up & Skin Care',
                    'Makeup',
                    'scat: Foundation',
                    'scat: Skincare',
                    'Serum',
                    'Serum and Facial Treatment',
                    'Serums',
                    'Skin Care',
                ],

                'Concealer' => [
                    'Beauty Cosmetics',
                    'Beauty Cosmetics Face',
                    'Beauty Face',
                    'Concealer',
                    'Face make up',
                    'Make Up & Skin Care',
                    'Makeup',
                    'scat: Concealer',
                ],

                'Blush' => [
                    'Beauty Cosmetics',
                    'Beauty Cosmetics Face',
                    'Beauty Selfcare',
                    'Blush',
                    'Blusher',
                    'Face make up',
                    'Make Up & Skin Care',
                    'Makeup',
                    'scat: Blush',
                ],

                'Eyebrows' => [
                    'Beauty Cosmetics',
                    'Beauty Cosmetics Eyes',
                    'Beauty Eyes',
                    'Eye Pencil',
                    'Eyebrow',
                    'Eyebrows',
                    'Eyebrows Pencil',
                    'scat: Eyebrows',
                ],

                'Face Serums' => [
                    'Beauty Cosmetics Face',
                    'Beauty Face',
                    'Beauty Selfcare',
                    'Beauty Selfcare Skincare',
                    'Face',
                    'Make Up & Skin Care',
                    'scat: Skincare',
                    'Serum',
                    'Serum and Facial Treatment',
                    'Serums',
                    'Skin Care',
                    'Skincare',
                ],

                'Face Cream' => [
                    'Beauty Cosmetics',
                    'Beauty Cosmetics Face',
                    'Beauty Face',
                    'Beauty Selfcare Skincare',
                    'Face Cream',
                    'Make Up & Skin Care',
                    'scat: Skincare',
                    'Skincare',
                ],

                'Body Lotion' => [
                    'Beauty Selfcare',
                    'Beauty Selfcare Bodycare',
                    'Beauty Selfcare Skincare',
                    'Body Lotion',
                    'scat: Skincare',
                    'Selfcare',
                    'Skincare',
                ],

                'Hand Cream' => [
                    'Beauty Niche Fragrances',
                    'Hand Cream',
                    'Niche fragrances',
                    'scat: Handcare',
                    'scat: Niche Fragrances',
                ],

                'Shampoo' => [
                    'Beauty Haircare',
                    'Beauty Selfcare',
                    'Beauty Selfcare Haircare',
                    'Beauty Selfcare Skincare',
                    'Hair Care',
                    'Hair Shampoo',
                    'Haircare',
                    'scat: Haircare',
                    'Selfcare',
                    'Shampoo',
                ],

                'Conditioner' => [
                    'Beauty Haircare',
                    'Beauty Selfcare',
                    'Beauty Selfcare Haircare',
                    'Beauty Selfcare Skincare',
                    'Hair Care',
                    'Hair Conditioner',
                    'Haircare',
                    'scat: Haircare',
                    'Selfcare',
                ],

                'Hair Treatments' => [
                    'Beauty Haircare',
                    'Beauty Selfcare',
                    'Beauty Selfcare Haircare',
                    'Beauty Selfcare Skincare',
                    'Hair Care',
                    'Haircare',
                    'scat: Haircare',
                    'Selfcare',
                ],

            ],
        ],
    ],
];
